name = "SVBCR"
author = "nuclearcrackhead239"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a97f518923d211c861c9ef0a525495f6c748ea904d76f60d70d090bf9f6c754c"

[versions]
forge = "37.1.1"
minecraft = "1.17.1"
