name = "SVBCR"
author = "nuclearcrackhead239"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "365a246090bc0290f0ca6d48ea766cbff7c8b844f1e63f52d61d83cd7c3d8549"

[versions]
forge = "37.1.1"
minecraft = "1.17.1"
