name = "SVBCR"
author = "nuclearcrackhead239"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53f9cdf961308b054b59980a8a57ac97da82190aabdd6d52623efea3c23abd21"

[versions]
forge = "37.1.1"
minecraft = "1.17.1"
